services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: habits
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:test1234@db:5432/habits

volumes:
  pgdata: